steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build','-t','$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO/ppa-ui:latest','-f','ui/Dockerfile','.']
  env:
  - 'VITE_API_BASE=$_VITE_API_BASE'
images:
- '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO/ppa-ui:latest'
